#![feature(abi_msp430_interrupt)]
#![doc = "Peripheral access API for MSP430FR2433 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
#[allow(unused_imports)]
use generic::*;
#[cfg(feature = "rt")]
pub use msp430_rt::interrupt;
#[doc = "Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "msp430-interrupt" {
    fn PORT2();
    fn PORT1();
    fn ADC();
    fn USCI_B0();
    fn USCI_A1();
    fn USCI_A0();
    fn WDT();
    fn RTC();
    fn TIMER3_A1();
    fn TIMER3_A0();
    fn TIMER2_A1();
    fn TIMER2_A0();
    fn TIMER1_A1();
    fn TIMER1_A0();
    fn TIMER0_A1();
    fn TIMER0_A0();
    fn UNMI();
    fn SYSNMI();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "msp430-interrupt" fn(),
    _reserved: u16,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
#[used]
pub static __INTERRUPTS: [Vector; 59] = [
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: PORT2 },
    Vector { _handler: PORT1 },
    Vector { _handler: ADC },
    Vector { _handler: USCI_B0 },
    Vector { _handler: USCI_A1 },
    Vector { _handler: USCI_A0 },
    Vector { _handler: WDT },
    Vector { _handler: RTC },
    Vector {
        _handler: TIMER3_A1,
    },
    Vector {
        _handler: TIMER3_A0,
    },
    Vector {
        _handler: TIMER2_A1,
    },
    Vector {
        _handler: TIMER2_A0,
    },
    Vector {
        _handler: TIMER1_A1,
    },
    Vector {
        _handler: TIMER1_A0,
    },
    Vector {
        _handler: TIMER0_A1,
    },
    Vector {
        _handler: TIMER0_A0,
    },
    Vector { _handler: UNMI },
    Vector { _handler: SYSNMI },
];
#[doc = r"Enumeration of all the interrupts. This enum is seldom used in application or library crates. It is present primarily for documenting the device's implemented interrupts."]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "41 - 0xFFDA Port 2"]
    PORT2 = 41,
    #[doc = "42 - 0xFFDC Port 1"]
    PORT1 = 42,
    #[doc = "43 - 0xFFDE ADC"]
    ADC = 43,
    #[doc = "44 - 0xFFE0 USCI B0 Receive/Transmit"]
    USCI_B0 = 44,
    #[doc = "45 - 0xFFE2 USCI A1 Receive/Transmit"]
    USCI_A1 = 45,
    #[doc = "46 - 0xFFE4 USCI A0 Receive/Transmit"]
    USCI_A0 = 46,
    #[doc = "47 - 0xFFE6 Watchdog Timer"]
    WDT = 47,
    #[doc = "48 - 0xFFE8 RTC"]
    RTC = 48,
    #[doc = "49 - 0xFFEA Timer3_A2 CC1, TA"]
    TIMER3_A1 = 49,
    #[doc = "50 - 0xFFEC Timer3_A2 CC0"]
    TIMER3_A0 = 50,
    #[doc = "51 - 0xFFEE Timer2_A2 CC1, TA"]
    TIMER2_A1 = 51,
    #[doc = "52 - 0xFFF0 Timer2_A2 CC0"]
    TIMER2_A0 = 52,
    #[doc = "53 - 0xFFF2 Timer1_A3 CC1-2, TA"]
    TIMER1_A1 = 53,
    #[doc = "54 - 0xFFF4 Timer1_A3 CC0"]
    TIMER1_A0 = 54,
    #[doc = "55 - 0xFFF6 Timer0_A3 CC1-2, TA"]
    TIMER0_A1 = 55,
    #[doc = "56 - 0xFFE8 Timer0_A3 CC0"]
    TIMER0_A0 = 56,
    #[doc = "57 - 0xFFFA User Non-maskable"]
    UNMI = 57,
    #[doc = "58 - 0xFFFC System Non-maskable"]
    SYSNMI = 58,
}
#[doc = "Port 3"]
pub type P3 = crate::Periph<p3::RegisterBlock, 0x0220>;
impl core::fmt::Debug for P3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P3").finish()
    }
}
#[doc = "Port 3"]
pub mod p3;
#[doc = "eUSCI_A0"]
pub type EUsciA0 = crate::Periph<e_usci_a0::RegisterBlock, 0x0500>;
impl core::fmt::Debug for EUsciA0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciA0").finish()
    }
}
#[doc = "eUSCI_A0"]
pub mod e_usci_a0;
#[doc = "eUSCI_A1"]
pub type EUsciA1 = crate::Periph<e_usci_a1::RegisterBlock, 0x0520>;
impl core::fmt::Debug for EUsciA1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciA1").finish()
    }
}
#[doc = "eUSCI_A1"]
pub mod e_usci_a1;
#[doc = "eUSCI_B0"]
pub type EUsciB0 = crate::Periph<e_usci_b0::RegisterBlock, 0x0540>;
impl core::fmt::Debug for EUsciB0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EUsciB0").finish()
    }
}
#[doc = "eUSCI_B0"]
pub mod e_usci_b0;
#[doc = "SFR Special Function Registers"]
pub type Sfr = crate::Periph<sfr::RegisterBlock, 0x0100>;
impl core::fmt::Debug for Sfr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sfr").finish()
    }
}
#[doc = "SFR Special Function Registers"]
pub mod sfr;
#[doc = "PMM Power Management System"]
pub type Pmm = crate::Periph<pmm::RegisterBlock, 0x0120>;
impl core::fmt::Debug for Pmm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pmm").finish()
    }
}
#[doc = "PMM Power Management System"]
pub mod pmm;
#[doc = "SYS System Module"]
pub type Sys = crate::Periph<sys::RegisterBlock, 0x0140>;
impl core::fmt::Debug for Sys {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sys").finish()
    }
}
#[doc = "SYS System Module"]
pub mod sys;
#[doc = "CS Clock System"]
pub type Cs = crate::Periph<cs::RegisterBlock, 0x0180>;
impl core::fmt::Debug for Cs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cs").finish()
    }
}
#[doc = "CS Clock System"]
pub mod cs;
#[doc = "FRCTL"]
pub type Frctl = crate::Periph<frctl::RegisterBlock, 0x01a0>;
impl core::fmt::Debug for Frctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Frctl").finish()
    }
}
#[doc = "FRCTL"]
pub mod frctl;
#[doc = "CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x01c0>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC"]
pub mod crc;
#[doc = "WDT_A"]
pub type WdtA = crate::Periph<wdt_a::RegisterBlock, 0x01cc>;
impl core::fmt::Debug for WdtA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WdtA").finish()
    }
}
#[doc = "WDT_A"]
pub mod wdt_a;
#[doc = "Port 1"]
pub type P1 = crate::Periph<p1::RegisterBlock, 0x0200>;
impl core::fmt::Debug for P1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P1").finish()
    }
}
#[doc = "Port 1"]
pub mod p1;
#[doc = "Port 2"]
pub type P2 = crate::Periph<p2::RegisterBlock, 0x0200>;
impl core::fmt::Debug for P2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P2").finish()
    }
}
#[doc = "Port 2"]
pub mod p2;
#[doc = "RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x0300>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "RTC"]
pub mod rtc;
#[doc = "TA0"]
pub type Ta0 = crate::Periph<ta0::RegisterBlock, 0x0380>;
impl core::fmt::Debug for Ta0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ta0").finish()
    }
}
#[doc = "TA0"]
pub mod ta0;
#[doc = "TA1"]
pub type Ta1 = crate::Periph<ta1::RegisterBlock, 0x03c0>;
impl core::fmt::Debug for Ta1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ta1").finish()
    }
}
#[doc = "TA1"]
pub mod ta1;
#[doc = "TA2"]
pub type Ta2 = crate::Periph<ta2::RegisterBlock, 0x0400>;
impl core::fmt::Debug for Ta2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ta2").finish()
    }
}
#[doc = "TA2"]
pub mod ta2;
#[doc = "TA3"]
pub type Ta3 = crate::Periph<ta3::RegisterBlock, 0x0440>;
impl core::fmt::Debug for Ta3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ta3").finish()
    }
}
#[doc = "TA3"]
pub mod ta3;
#[doc = "MPY32"]
pub type Mpy32 = crate::Periph<mpy32::RegisterBlock, 0x04c0>;
impl core::fmt::Debug for Mpy32 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mpy32").finish()
    }
}
#[doc = "MPY32"]
pub mod mpy32;
#[doc = "BAKMEM"]
pub type Bakmem = crate::Periph<bakmem::RegisterBlock, 0x0660>;
impl core::fmt::Debug for Bakmem {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bakmem").finish()
    }
}
#[doc = "BAKMEM"]
pub mod bakmem;
#[doc = "ADC"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x0700>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "ADC"]
pub mod adc;
#[doc = "Device descriptors (TLV)"]
pub type Tlv = crate::Periph<tlv::RegisterBlock, 0x1a00>;
impl core::fmt::Debug for Tlv {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tlv").finish()
    }
}
#[doc = "Device descriptors (TLV)"]
pub mod tlv;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "P3"]
    pub p3: P3,
    #[doc = "E_USCI_A0"]
    pub e_usci_a0: EUsciA0,
    #[doc = "E_USCI_A1"]
    pub e_usci_a1: EUsciA1,
    #[doc = "E_USCI_B0"]
    pub e_usci_b0: EUsciB0,
    #[doc = "SFR"]
    pub sfr: Sfr,
    #[doc = "PMM"]
    pub pmm: Pmm,
    #[doc = "SYS"]
    pub sys: Sys,
    #[doc = "CS"]
    pub cs: Cs,
    #[doc = "FRCTL"]
    pub frctl: Frctl,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "WDT_A"]
    pub wdt_a: WdtA,
    #[doc = "P1"]
    pub p1: P1,
    #[doc = "P2"]
    pub p2: P2,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "TA0"]
    pub ta0: Ta0,
    #[doc = "TA1"]
    pub ta1: Ta1,
    #[doc = "TA2"]
    pub ta2: Ta2,
    #[doc = "TA3"]
    pub ta3: Ta3,
    #[doc = "MPY32"]
    pub mpy32: Mpy32,
    #[doc = "BAKMEM"]
    pub bakmem: Bakmem,
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "TLV"]
    pub tlv: Tlv,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            p3: P3::steal(),
            e_usci_a0: EUsciA0::steal(),
            e_usci_a1: EUsciA1::steal(),
            e_usci_b0: EUsciB0::steal(),
            sfr: Sfr::steal(),
            pmm: Pmm::steal(),
            sys: Sys::steal(),
            cs: Cs::steal(),
            frctl: Frctl::steal(),
            crc: Crc::steal(),
            wdt_a: WdtA::steal(),
            p1: P1::steal(),
            p2: P2::steal(),
            rtc: Rtc::steal(),
            ta0: Ta0::steal(),
            ta1: Ta1::steal(),
            ta2: Ta2::steal(),
            ta3: Ta3::steal(),
            mpy32: Mpy32::steal(),
            bakmem: Bakmem::steal(),
            adc: Adc::steal(),
            tlv: Tlv::steal(),
        }
    }
}
